apiVersion: v1
kind: Pod
metadata:
  name: helloworld
  labels:
    app: helloworld
spec:
  containers:
  - name: helloworld
    image: registry.gitlab.com/mkarg/javaonkubernetes:master
    imagePullPolicy: Always
    ports:
      - name: hello-port
        containerPort: 8080
    livenessProbe:
      httpGet:
        path: /question/health
        port: hello-port
    envFrom:
      - configMapRef:
          name: helloworld
